import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MenuBar from '../../components/menu-bar/manu-bar'
import img from '../../public/background.webp'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className={inter.className} style={{ backgroundImage: `url(${img.src})` }} >
        <MenuBar />
        {children}
      </body>
    </html>
  )
}

